# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flight_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'flight_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66light_service.proto\x12\x06\x66light\"!\n\x10\x43heckUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"#\n\x11\x43heckUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"\x1f\n\x0eGetUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"v\n\x0fGetUserResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x13\n\x0b\x66iscal_code\x18\x04 \x01(\t\x12\x11\n\tbank_info\x18\x05 \x01(\t\x12\r\n\x05\x66ound\x18\x06 \x01(\x08\x32\x8f\x01\n\x0bUserService\x12\x42\n\tCheckUser\x12\x18.flight.CheckUserRequest\x1a\x19.flight.CheckUserResponse\"\x00\x12<\n\x07GetUser\x12\x16.flight.GetUserRequest\x1a\x17.flight.GetUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flight_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKUSERREQUEST']._serialized_start=32
  _globals['_CHECKUSERREQUEST']._serialized_end=65
  _globals['_CHECKUSERRESPONSE']._serialized_start=67
  _globals['_CHECKUSERRESPONSE']._serialized_end=102
  _globals['_GETUSERREQUEST']._serialized_start=104
  _globals['_GETUSERREQUEST']._serialized_end=135
  _globals['_GETUSERRESPONSE']._serialized_start=137
  _globals['_GETUSERRESPONSE']._serialized_end=255
  _globals['_USERSERVICE']._serialized_start=258
  _globals['_USERSERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
