# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import user_manager_pb2 as user__manager__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckUser = channel.unary_unary(
                '/flight.UserService/CheckUser',
                request_serializer=user__manager__pb2.CheckUserRequest.SerializeToString,
                response_deserializer=user__manager__pb2.CheckUserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/flight.UserService/GetUser',
                request_serializer=user__manager__pb2.GetUserRequest.SerializeToString,
                response_deserializer=user__manager__pb2.GetUserResponse.FromString,
                )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUser,
                    request_deserializer=user__manager__pb2.CheckUserRequest.FromString,
                    response_serializer=user__manager__pb2.CheckUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=user__manager__pb2.GetUserRequest.FromString,
                    response_serializer=user__manager__pb2.GetUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flight.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flight.UserService/CheckUser',
            user__manager__pb2.CheckUserRequest.SerializeToString,
            user__manager__pb2.CheckUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flight.UserService/GetUser',
            user__manager__pb2.GetUserRequest.SerializeToString,
            user__manager__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CollectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CleanupUser = channel.unary_unary(
                '/flight.CollectorService/CleanupUser',
                request_serializer=user__manager__pb2.CleanupUserRequest.SerializeToString,
                response_deserializer=user__manager__pb2.CleanupUserResponse.FromString,
                )
        self.RemoveAirportInterest = channel.unary_unary(
                '/flight.CollectorService/RemoveAirportInterest',
                request_serializer=user__manager__pb2.RemoveAirportInterestRequest.SerializeToString,
                response_deserializer=user__manager__pb2.RemoveAirportInterestResponse.FromString,
                )


class CollectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CleanupUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAirportInterest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CleanupUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupUser,
                    request_deserializer=user__manager__pb2.CleanupUserRequest.FromString,
                    response_serializer=user__manager__pb2.CleanupUserResponse.SerializeToString,
            ),
            'RemoveAirportInterest': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAirportInterest,
                    request_deserializer=user__manager__pb2.RemoveAirportInterestRequest.FromString,
                    response_serializer=user__manager__pb2.RemoveAirportInterestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flight.CollectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CollectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CleanupUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flight.CollectorService/CleanupUser',
            user__manager__pb2.CleanupUserRequest.SerializeToString,
            user__manager__pb2.CleanupUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveAirportInterest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flight.CollectorService/RemoveAirportInterest',
            user__manager__pb2.RemoveAirportInterestRequest.SerializeToString,
            user__manager__pb2.RemoveAirportInterestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
