# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_manager.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_manager.proto\x12\x06\x66light\"!\n\x10\x43heckUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"#\n\x11\x43heckUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"\x1f\n\x0eGetUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"v\n\x0fGetUserResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x13\n\x0b\x66iscal_code\x18\x04 \x01(\t\x12\x11\n\tbank_info\x18\x05 \x01(\t\x12\r\n\x05\x66ound\x18\x06 \x01(\x08\"#\n\x12\x43leanupUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"7\n\x13\x43leanupUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"C\n\x1cRemoveAirportInterestRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x14\n\x0c\x61irport_code\x18\x02 \x01(\t\"A\n\x1dRemoveAirportInterestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8f\x01\n\x0bUserService\x12\x42\n\tCheckUser\x12\x18.flight.CheckUserRequest\x1a\x19.flight.CheckUserResponse\"\x00\x12<\n\x07GetUser\x12\x16.flight.GetUserRequest\x1a\x17.flight.GetUserResponse\"\x00\x32\xc4\x01\n\x10\x43ollectorService\x12H\n\x0b\x43leanupUser\x12\x1a.flight.CleanupUserRequest\x1a\x1b.flight.CleanupUserResponse\"\x00\x12\x66\n\x15RemoveAirportInterest\x12$.flight.RemoveAirportInterestRequest\x1a%.flight.RemoveAirportInterestResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_manager_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKUSERREQUEST']._serialized_start=30
  _globals['_CHECKUSERREQUEST']._serialized_end=63
  _globals['_CHECKUSERRESPONSE']._serialized_start=65
  _globals['_CHECKUSERRESPONSE']._serialized_end=100
  _globals['_GETUSERREQUEST']._serialized_start=102
  _globals['_GETUSERREQUEST']._serialized_end=133
  _globals['_GETUSERRESPONSE']._serialized_start=135
  _globals['_GETUSERRESPONSE']._serialized_end=253
  _globals['_CLEANUPUSERREQUEST']._serialized_start=255
  _globals['_CLEANUPUSERREQUEST']._serialized_end=290
  _globals['_CLEANUPUSERRESPONSE']._serialized_start=292
  _globals['_CLEANUPUSERRESPONSE']._serialized_end=347
  _globals['_REMOVEAIRPORTINTERESTREQUEST']._serialized_start=349
  _globals['_REMOVEAIRPORTINTERESTREQUEST']._serialized_end=416
  _globals['_REMOVEAIRPORTINTERESTRESPONSE']._serialized_start=418
  _globals['_REMOVEAIRPORTINTERESTRESPONSE']._serialized_end=483
  _globals['_USERSERVICE']._serialized_start=486
  _globals['_USERSERVICE']._serialized_end=629
  _globals['_COLLECTORSERVICE']._serialized_start=632
  _globals['_COLLECTORSERVICE']._serialized_end=828
# @@protoc_insertion_point(module_scope)
